empty= [ ] .
prog= block ; .
block= [const name = number [, const name = number] ; ]
       [var name [, var name] ; ] 
       [procedure name ; block ; ]
       operator .
operator= name := expression,
          call name,
          begin operator [operator ; ] end,
          if condition then operator,
          while condition do operator,
          empty .
